import type { Metadata } from "next"
import { absoluteUrl } from "@/lib/site-url"

/** A share image named outright, rather than generated by opengraph-image.tsx. */
type ShareImage = {
  url: string
  width: number
  height: number
  alt: string
  type?: string
  secureUrl?: string
}

/**
 * Per-page canonical + social tags. Without these, pages inherit the root
 * layout's homepage canonical and OG card, so every URL reports itself as a
 * duplicate of the homepage and shares as a generic "AI Atlas" preview.
 */
export function pageMetadata({
  title,
  description,
  path,
  image,
  type = "website",
  publishedTime,
  modifiedTime,
}: {
  title: string
  description: string
  path: string
  image?: string | ShareImage | null
  type?: "website" | "article"
  /** article only — LinkedIn and Google both read the date off these. */
  publishedTime?: string
  modifiedTime?: string
}): Metadata {
  const canonical = absoluteUrl(path)
  const resolvedImage =
    typeof image === "string" ? (image.trim() || undefined) : (image ?? undefined)
  return {
    title,
    description,
    alternates: { canonical },
    openGraph: {
      type,
      url: canonical,
      title,
      description,
      ...(type === "article" ? { publishedTime, modifiedTime } : {}),
      // Omit `images` entirely when there's no explicit one: setting it to
      // undefined reads as "this page has no image" and suppresses the
      // opengraph-image.tsx file convention, leaving shared links imageless.
      ...(resolvedImage ? { images: [resolvedImage] } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      // Naming an openGraph image outright suppresses the file convention for
      // both cards, so Twitter needs the same one repeated or it loses its
      // image. Callers passing a bare string URL keep their existing output.
      ...(typeof resolvedImage === "object" ? { images: [resolvedImage] } : {}),
    },
  }
}
